import { Prisma } from "@prisma/client";
import Head from "next/head";
import { GridList } from "~/components/GridList/GridList";
import { api } from "~/utils/api";

type TSet = Prisma.BillSetGetPayload<{ include: { owners: true } }>;

export default function SetsPage() {
  const sets = api.billSets.getAllSets.useQuery();
  return (
    <>
      <Head>
        <title>Kategorie</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen items-center px-5 py-4">
        {sets.data && (
          <GridList<TSet>
            title={"Zestawy"}
            data={sets.data}
            itemType={"set"}
            rows={2}
            cols={4}
          />
        )}
      </main>
    </>
  );
}
