import Head from "next/head";
import { GridList } from "~/components/GridList/GridList";

type TSet = {
  id: string;
  name: string;
  bills: never[];
  value: number;
};

export default function SetsPage() {
  const sets = [
    { id: "1", title: "something", name: "remont", bills: [], value: 250.49 },
    { id: "2", title: "something", name: "wyjazd", bills: [], value: 137.37 },
  ];

  return (
    <>
      <Head>
        <title>Kategorie</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen items-center px-5 py-4">
        <GridList<TSet>
          title={"Zestawy"}
          data={sets}
          itemType={"set"}
          rows={2}
          cols={4}
        />
      </main>
    </>
  );
}
