import { Bill, Prisma, User } from "@prisma/client";
import Head from "next/head";
import { AddSetForm } from "~/components/AddSetForm/AddSetForm";
import { GridList } from "~/components/GridList/GridList";
import { api } from "~/utils/api";
import { useState, useEffect } from "react";
import { useRouter } from "next/router";

type TSet = Prisma.BillSetGetPayload<{ include: { owners: true } }>;

export default function SetsPage() {
  const [billSets, setBillSets] = useState<TSet[]>();
  const { data } = api.billSets.getAllSets.useQuery();
  const addNewSetGetAll = api.billSets.addNewSetReturnAll.useMutation();
  const router = useRouter();

  const submitForm = async (
    name: string,
    selectedBills?: Bill[],
    selectedUsers?: User[]
  ) => {
    if (!name) return;

    if (selectedBills && selectedUsers) {
      const result = await addNewSetGetAll.mutateAsync({
        name,
        bills: selectedBills,
        users: selectedUsers,
      });
      setBillSets(result);
    } else if (selectedBills && !selectedUsers) {
      const result = await addNewSetGetAll.mutateAsync({
        name,
        bills: selectedBills,
      });
      setBillSets(result);
    } else if (!selectedBills && selectedUsers) {
      const result = await addNewSetGetAll.mutateAsync({
        name,
        users: selectedUsers,
      });
      setBillSets(result);
    } else {
      const result = await addNewSetGetAll.mutateAsync({
        name,
      });
      setBillSets(result);
    }
  };

  useEffect(() => {
    setBillSets(data);
  }, [data]);

  return (
    <>
      <Head>
        <title>Zestawy</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="grid h-screen grid-cols-5 px-5 py-4">
        <div className="col-span-1 flex flex-col items-center py-5">
          <AddSetForm
            onSubmit={submitForm}
            openFormBtn={router.query.id === "add-set" ? false : true}
          />
        </div>
        <div className="col-span-4 ">
          {billSets && (
            <GridList<TSet>
              title={"Zestawy"}
              data={billSets}
              itemType={"set"}
              rows={2}
              cols={3}
            />
          )}
        </div>
      </main>
    </>
  );
}
