import Head from "next/head";
import Link from "next/link";
import { CustomList } from "~/components/CustomList/CustomList";
import { Title } from "~/components/Title/Title";
import { BillWithProducts } from "~/types/types";
import { api } from "~/utils/api";

export default function Dashboard() {
  const billsByDate = api.bills.getBillsByAddedDate.useQuery(1);
  const billsToPay = api.bills.getNotPaidBills.useQuery(10);

  return (
    <>
      <Head>
        <title>Tablica</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative grid h-screen grid-cols-4">
        <Link href="/dashboard/add-bill" className="absolute right-0 top-0">
          Nowy rachunek
        </Link>
        <div className="span col-span-2 flex items-center justify-center">
          <div>Ostatnio zaktualizowane zestawy</div>
          <div></div>
        </div>
        <div className="w-full px-10">
          <Title text="Nadchodzące wydatki" />
          {billsToPay.data && (
            <CustomList<BillWithProducts>
              data={billsToPay.data}
              itemsPerPage={4}
              listType="to-pay"
            />
          )}
        </div>
        <div className="w-full px-10">
          <Title text="Ostatnio dodane" />
          {billsByDate.data && (
            <CustomList<BillWithProducts>
              data={billsByDate.data}
              itemsPerPage={4}
              listType="last-added"
            />
          )}
        </div>
      </main>
    </>
  );
}
