import Head from "next/head";

export default function YearsPage() {
  return (
    <>
      <Head>
        <title>Kategorie</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen items-center justify-center px-5 py-4">
        <div>years</div>
      </main>
    </>
  );
}
