import Head from "next/head";
import { BillCard } from "~/components/BillCard/BillCard";
import type { BillWithProducts } from "~/types/types";
import { api } from "~/utils/api";

export default function Dashboard() {
  const billsWithProducts = api.bills.getBillsWithProducts.useQuery();

  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen flex-col px-5 py-4">
        <div>bills</div>
        <ul className="grid grid-cols-10 px-20 py-2">
          {billsWithProducts &&
            billsWithProducts.data?.map((bill: BillWithProducts) => {
              return <BillCard {...bill} key={bill.id} />;
            })}
        </ul>
      </main>
    </>
  );
}
