import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { BillCard } from "~/components/BillCard/BillCard";
import { api } from "~/utils/api";

export default function CategoryPage() {
  const router = useRouter();
  const categoryName = router.query.name as string;

  const bills = api.bills.getBillsByCategory.useQuery({ name: categoryName });

  return (
    <>
      <Head>
        <title>{categoryName}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="grid grid-cols-4">
        <div className="col-span-2">
          <Link href={`${router.asPath}/add-bill`}>Dodaj rachunek</Link>
        </div>
        <div>
          <ul className="flex flex-col items-center gap-8">
            {bills &&
              bills.data?.map((el) => {
                return <BillCard {...el} key={el.id} />;
              })}
          </ul>
        </div>
      </main>
    </>
  );
}
