import Head from "next/head";
import { AddBillForm } from "~/components/AddBillForm/AddBillForm";

export default function AddBillPage() {
  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <h1 className="text-3xl">add bill</h1>
        <AddBillForm />
      </main>
    </>
  );
}
