import { Product } from "@prisma/client";
import Head from "next/head";
import { ChangeEvent, useState } from "react";
import { AddProductForm } from "~/components/AddProductForm/AddProductForm";
import { SignInBtn } from "~/components/SignInBtn/SignInBtn";
import { api } from "~/utils/api";
import { sumValues } from "~/utils/sumValues";

export default function AddBillPage() {
  const products = api.products.getProducts.useQuery();
  const [name, setName] = useState<string>("");
  const [items, setItems] = useState<Product[]>([]);
  const [value, setValue] = useState<number>(0);
  const [isPaid, setIsPaid] = useState<boolean>(false);

  const handleCheckbox = (
    e: React.FormEvent<HTMLInputElement>,
    el: Product
  ) => {
    const products = items;

    e.currentTarget.checked
      ? products.push(el)
      : products.filter((item) => el.id !== item.id);

    setItems(products);

    const sumValue = sumValues(products);

    setValue(sumValue);
  };

  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <h1 className="text-3xl">add bill</h1>
        <div>
          <form className="flex flex-col gap-4">
            <input
              type="text"
              placeholder="name"
              onChange={(e) => setName(e.target.value)}
            />
            <div>
              {products &&
                products.data?.map((el) => {
                  return (
                    <label htmlFor={el.name} key={el.id}>
                      {el.name}
                      <input
                        type="checkbox"
                        id={el.name}
                        className=" ml-3"
                        onChange={(e) => handleCheckbox(e, el)}
                      />
                    </label>
                  );
                })}
            </div>
            <label htmlFor="isPaid">
              Zapłacone?
              <input
                type="checkbox"
                id="isPaid"
                className=" ml-3"
                checked={isPaid}
                onChange={() => setIsPaid((prev) => !prev)}
              />
            </label>
          </form>

          <div>value: {value}</div>
        </div>
      </main>
    </>
  );
}
