import Head from "next/head";

export default function AnalyticsPage() {
  return (
    <>
      <Head>
        <title>Analytics</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>Analytics</div>
      </main>
    </>
  );
}
