import { type Product } from "@prisma/client";
import Head from "next/head";
import { BillCard } from "~/components/BillCard/BillCard";
import type { BillWithProducts } from "~/types/types";
import { api } from "~/utils/api";

export default function Dashboard() {
  const billsWithProducts = api.bills.getBillsWithProducts.useQuery();

  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div>bills</div>
        <ul>
          {billsWithProducts &&
            billsWithProducts.data?.map((bill: BillWithProducts) => {
              return <BillCard {...bill} key={bill.id} />;
            })}
        </ul>
      </main>
    </>
  );
}
