import Head from "next/head";
import { api } from "~/utils/api";

export default function Dashboard() {
  const bills = api.bills.getBills.useQuery();

  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div>bills</div>
        <ul>
          {bills &&
            bills.data?.map((bill) => {
              return (
                <li key={bill.id}>
                  <span>{bill.name}</span>
                </li>
              );
            })}
        </ul>
      </main>
    </>
  );
}
