import Head from "next/head";

export default function Dashboard() {
  return (
    <>
      <Head>
        <title>Tablica</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-grow flex-col items-center justify-center">
        <div>Tablica</div>
      </main>
    </>
  );
}
