import Head from "next/head";
import { api } from "~/utils/api";

export default function Dashboard() {
  const products = api.products.getProducts.useQuery();

  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-grow flex-col items-center justify-center">
        <div>dashboard</div>
      </main>
    </>
  );
}
