import { useSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";
import { ProtectedRoute } from "~/components/ProtectedRoute/ProtectedRoute";
import { SignInBtn } from "~/components/SignInBtn/SignInBtn";

export default function Dashboard() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div>dashboard</div>
        <SignInBtn />
      </main>
    </>
  );
}
