import Head from "next/head";
import { AddBillForm } from "~/components/AddBillForm/AddBillForm";
import { AddProductForm } from "~/components/AddProductForm/AddProductForm";
import { ProductsContext, ProductsProvider } from "~/context/ProductsContext";

export default function AddBillPage() {
  return (
    <>
      <Head>
        <title>Tablica</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-grow flex-col items-center justify-center">
        <div>add bill</div>
        <form></form>
        <ProductsProvider>
          <AddBillForm />
        </ProductsProvider>
      </main>
    </>
  );
}
