import Head from "next/head";
import { AddBillForm } from "~/components/AddBillForm/AddBillForm";
import { ProductsProvider } from "~/context/ProductsContext";

export default function AddBillPage() {
  return (
    <>
      <Head>
        <title>Tablica</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="sm sm flex flex-grow flex-col items-center">
        <ProductsProvider>
          <AddBillForm />
        </ProductsProvider>
      </main>
    </>
  );
}
