import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { api } from "~/utils/api";

export default function CategoryPage() {
  const router = useRouter();
  const categoryName = router.query.id as string;

  const bills = api.bills.getBillsByCategory.useQuery({ name: categoryName });

  return (
    <>
      <Head>
        <title>{categoryName}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Link href={`${router.asPath}/add-bill`}>Dodaj rachunek</Link>
        <ul>
          {bills &&
            bills.data?.map((el) => {
              return <li key={el.id}>{el.name}</li>;
            })}
        </ul>
      </main>
    </>
  );
}
